default: &default
  database: depot1
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 123QWEasd
 
  
development:
  <<: *default


 
test:
  <<: *default
 


production:
  <<: *default